// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIMt5yhBLSWQroZ1GoRslnmc4vSjWA5gw',
    appId: '1:319065643401:web:4e75d9b9499faef83a2958',
    messagingSenderId: '319065643401',
    projectId: 'bluex-browser',
    authDomain: 'bluex-browser.firebaseapp.com',
    databaseURL: 'https://bluex-browser-default-rtdb.firebaseio.com',
    storageBucket: 'bluex-browser.firebasestorage.app',
    measurementId: 'G-CW8SZZTJYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVqxF9326BCskonrz0zJvRFP-HIxbHhcA',
    appId: '1:319065643401:android:f29a119100117fec3a2958',
    messagingSenderId: '319065643401',
    projectId: 'bluex-browser',
    databaseURL: 'https://bluex-browser-default-rtdb.firebaseio.com',
    storageBucket: 'bluex-browser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-LaaumZLsfZjiEjHcGavS1ERA4dvSMJU',
    appId: '1:319065643401:ios:a89cd5d67177de853a2958',
    messagingSenderId: '319065643401',
    projectId: 'bluex-browser',
    databaseURL: 'https://bluex-browser-default-rtdb.firebaseio.com',
    storageBucket: 'bluex-browser.firebasestorage.app',
    iosBundleId: 'com.example.browserapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-LaaumZLsfZjiEjHcGavS1ERA4dvSMJU',
    appId: '1:319065643401:ios:a89cd5d67177de853a2958',
    messagingSenderId: '319065643401',
    projectId: 'bluex-browser',
    databaseURL: 'https://bluex-browser-default-rtdb.firebaseio.com',
    storageBucket: 'bluex-browser.firebasestorage.app',
    iosBundleId: 'com.example.browserapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIMt5yhBLSWQroZ1GoRslnmc4vSjWA5gw',
    appId: '1:319065643401:web:e8a0d8bcc936df0e3a2958',
    messagingSenderId: '319065643401',
    projectId: 'bluex-browser',
    authDomain: 'bluex-browser.firebaseapp.com',
    databaseURL: 'https://bluex-browser-default-rtdb.firebaseio.com',
    storageBucket: 'bluex-browser.firebasestorage.app',
    measurementId: 'G-7C4VLQ6DYZ',
  );

}