// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTD57nROv3FbZA1BL0H8JiPkJsuVJQbJI',
    appId: '1:195384976178:web:9ab7bacc5e82829612ad2b',
    messagingSenderId: '195384976178',
    projectId: 'test-51a88',
    authDomain: 'test-51a88.firebaseapp.com',
    storageBucket: 'test-51a88.firebasestorage.app',
    measurementId: 'G-2WHP011G25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1USmylZzbEw0Q_wZPVPqJdKHdcfNtr4',
    appId: '1:195384976178:android:a119a0319394c14412ad2b',
    messagingSenderId: '195384976178',
    projectId: 'test-51a88',
    storageBucket: 'test-51a88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKMQzU9SJ2GldrKtjF15okrKfgKiRqH3I',
    appId: '1:195384976178:ios:7a15bf31b5f1faf812ad2b',
    messagingSenderId: '195384976178',
    projectId: 'test-51a88',
    storageBucket: 'test-51a88.firebasestorage.app',
    iosBundleId: 'com.example.browserapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKMQzU9SJ2GldrKtjF15okrKfgKiRqH3I',
    appId: '1:195384976178:ios:7a15bf31b5f1faf812ad2b',
    messagingSenderId: '195384976178',
    projectId: 'test-51a88',
    storageBucket: 'test-51a88.firebasestorage.app',
    iosBundleId: 'com.example.browserapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTD57nROv3FbZA1BL0H8JiPkJsuVJQbJI',
    appId: '1:195384976178:web:0fd29982fb16419012ad2b',
    messagingSenderId: '195384976178',
    projectId: 'test-51a88',
    authDomain: 'test-51a88.firebaseapp.com',
    storageBucket: 'test-51a88.firebasestorage.app',
    measurementId: 'G-FJVRV4MP5X',
  );
}
